spring:
  application:
    name: customers-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://spring-petclinic-config-server-service.spring-petclinic.svc.cluster.local:8888/}


---
spring:
  config:
    activate:
      on-profile: docker
    import: optional:configserver:${CONFIG_SERVER_URL:http://spring-petclinic-config-server-service.spring-petclinic.svc.cluster.local:8888/}
