server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI:https://github.com/22120207/spring-petclinic-microservices-config}
          default-label: main
        native:
          searchLocations: file://${GIT_REPO}
