spring:
  application:
    name: admin-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://spring-petclinic-config-server-service:8888}


---
spring:
  config:
    activate:
      on-profile: docker
    import: optional:configserver:${CONFIG_SERVER_URL:http://spring-petclinic-config-server-service:8888}